# Generated by Django 4.0.5 on 2022-07-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField()),
                ('death_year', models.IntegerField()),
                ('study_program', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['birth_year'],
                'abstract': False,
            },
        ),
    ]
