# Generated by Django 4.0.5 on 2022-07-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide_4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField()),
                ('death_year', models.IntegerField()),
                ('research', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['birth_year'],
                'abstract': False,
            },
        ),
    ]
