# Generated by Django 4.0.5 on 2022-07-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide_4', '0003_universityplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='places',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', to='models_guide_4.universityplaces'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='places',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', to='models_guide_4.universityplaces'),
        ),
    ]
