# Generated by Django 4.0.5 on 2022-07-09 17:22

from django.db import migrations, models
import models_guide_3.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_id', models.IntegerField(validators=[models_guide_3.models.is_even])),
                ('custom_even_id', models_guide_3.models.EvenInteger()),
            ],
        ),
    ]
