# Generated by Django 4.0.5 on 2022-07-09 18:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide_3', '0003_alter_person_3_options_alter_person_3_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField()),
                ('death_year', models.IntegerField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='person_3',
            managers=[
                ('people', django.db.models.manager.Manager()),
            ],
        ),
    ]
