# Generated by Django 4.0.5 on 2022-07-13 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'proxies',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=199)),
                ('proxy', models.ForeignKey(default='default proxy', on_delete=django.db.models.deletion.SET_DEFAULT, to='mongo_app.proxy')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
