# Generated by Django 4.0.5 on 2022-07-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_myclubuser_venue_event_attendees_alter_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclubuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Adress'),
        ),
    ]
