# Generated by Django 4.0.5 on 2022-07-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide_2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mother',
        ),
    ]
