# Generated by Django 4.0.5 on 2022-07-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide_2', '0003_person_mother_alter_person_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='siblings',
            field=models.ManyToManyField(blank=True, null=True, related_name='ssiblings', to='models_guide_2.person'),
        ),
    ]
