# Generated by Django 4.0.5 on 2022-07-09 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide_2', '0002_remove_person_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models_guide_2.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='ss', max_length=20),
        ),
    ]
