# Generated by Django 4.0.5 on 2022-07-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_guide_3', '0002_person_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person_3',
            options={'ordering': ['birth_year']},
        ),
        migrations.AlterModelTable(
            name='person_3',
            table='person',
        ),
    ]
